language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmatheval-dev
script: 
  - ./configure
  - make
  - PATH=$PATH:$PWD/src/lib make -C regtest 
