language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmatheval-dev
  - sudo apt-get install -y doxygen
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y texlive-fonts-extra
install: 
  - ./configure
  - make
  - make doc
  - sudo make install
script:
  - make -C regtest 
