language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmatheval-dev
install: 
  - ./configure CXX=$(which $CXX) CC=$(which $CC)
  - make
  - sudo -make install
script:
  - make -C regtest 
