language: cpp
env:
  - CC=mpicc CXX=mpic++
  - CC=clang CXX=clang++
  - CC=gcc CXX=g++
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopenmpi-dev openmpi-bin
  - sudo apt-get install -y libmatheval-dev
  - sudo apt-get install -y doxygen
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y texlive-fonts-extra
  - sudo apt-get install -y texlive-full
install: 
  - touch src/crystallization.on src/manyrestraints.on
  - ./configure CXX=$(which $CXX) CC=$(which $CC)
  - make
  - make doc > makedoc.out
  - sudo make install
script:
  - make -C regtest 
