language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmatheval-dev
  - sudo apt-get install -y doxygen
  - sudo apt-get install -y graphviz
install: 
  - ./configure
  - make
  - make doc
script:
  - source sourceme.sh
  - make -C regtest 
